# Generated by Django 4.2 on 2023-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0004_alter_calendar_end_date_alter_calendar_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='availability',
            field=models.ManyToManyField(blank=True, to='swimapp.availability'),
        ),
    ]
