# Generated by Django 4.2.2 on 2023-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0005_alter_instructor_availability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='Lesson',
        ),
    ]
