# Generated by Django 4.2.2 on 2023-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0008_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='swimmer',
            field=models.ManyToManyField(blank=True, to='swimapp.swimmer'),
        ),
    ]
